/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ArticleCard: typeof import('./components/cards/ArticleCard.vue')['default']
    ArticleSection: typeof import('./components/ArticleSection.vue')['default']
    ArticlesSection: typeof import('./components/sections/ArticlesSection.vue')['default']
    CloseIcon: typeof import('./components/icons/CloseIcon.vue')['default']
    CustomMenuBar: typeof import('./components/CustomMenuBar.vue')['default']
    FloatingFooter: typeof import('./components/FloatingFooter.vue')['default']
    LocationButton: typeof import('./components/LocationButton.vue')['default']
    NavBar: typeof import('./components/NavBar.vue')['default']
    Newsletter: typeof import('./components/modals/Newsletter.vue')['default']
    PhoneIcon: typeof import('./components/icons/PhoneIcon.vue')['default']
    PrimaryButton: typeof import('./components/PrimaryButton.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollDown: typeof import('./components/ScrollDown.vue')['default']
    ScrollUp: typeof import('./components/ScrollUp.vue')['default']
    SocialLinks: typeof import('./components/SocialLinks.vue')['default']
    TheFooter: typeof import('./components/TheFooter.vue')['default']
    TheHeader: typeof import('./components/TheHeader.vue')['default']
    TheInput: typeof import('./components/TheInput.vue')['default']
    TopBar: typeof import('./components/TopBar.vue')['default']
    WideArticleCard: typeof import('./components/cards/WideArticleCard.vue')['default']
    WorksGallery: typeof import('./components/works/WorksGallery.vue')['default']
  }
}
