/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ArticleCard: typeof import('./components/cards/ArticleCard.vue')['default']
    ArticleSection: typeof import('./components/ArticleSection.vue')['default']
    NavBar: typeof import('./components/NavBar.vue')['default']
    PhoneIcon: typeof import('./components/icons/PhoneIcon.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheFooter: typeof import('./components/TheFooter.vue')['default']
    TheHeader: typeof import('./components/TheHeader.vue')['default']
    TheInput: typeof import('./components/TheInput.vue')['default']
    TopBar: typeof import('./components/TopBar.vue')['default']
  }
}
